name: Build and Deploy
run-name: ${{ github.actor }} start worflow 2

on:
 workflow_dispatch:
 push:
  branches:
    - main
  path: ./src

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 16
      - run: npm install -g @angular/cli
      - run: ng build
      - run: ls